# Dev Profile Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skku-table-dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Initial baseline"
    locations: 
      - classpath:db/migration
      - classpath:db/seed/dev
    validate-on-migrate: false
    table: flyway_schema_history

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE