spring:
  application:
    name: skku-table-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/skku-table}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

server:
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}