spring:
  profiles:
    active: test
  
  datasource:
    url: jdbc:mysql://localhost:3306/skku-table-test
    username: root
    password: 1234
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration  # test에서는 seed 데이터 제외