spring:
  
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  
  flyway:
    enabled: true
    baseline-on-migrate: true  # 프로덕션에서는 false
    locations:
      - classpath:db/migration  # prod에서는 seed 데이터 제외
      - classpath:db/dev/seed
    validate-on-migrate: true

logging:
  level:
    root: WARN
    com.skkutable: INFO